### ISSUE TITLE
Add a note about setup duration

### ISSUE THREAD

**Issue by chimeno** [wagtail/vagrant-wagtail-develop#4]
When running provision for the first time, the setup took more than 15 minutes in my case, so we can make a note in the README about that.
I was tempted to stopped it, so it can be useful for others.
What about?
**Note: the first time you setup, it can take a while to fetch and build all dependencies, you could go for a coffee in the meantime :)**

**Comment by gasman** [comment]
Thanks for the suggestion @chimeno! Have added the note as suggested, and also fixed (in fecce09facc47e4af8c62628b5416246e363e858) one of the biggest offenders for the long setup time - `npm install` now happens at the end, so that the huge `.node_modules` folder doesn't slow down pip installation. (On my machine this takes the build down from 29 minutes to 17.)
